openapi: 3.0.4
info:
  title: Password Generator
  description: >-
    Password Generator is a simple tool for generating passwords. It returns the
    generated password.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/passwordgenerator:
    get:
      summary: Generate Password
      description: Generate passwords with a specified length and complexity
      operationId: passwordgenerator
      parameters:
        - name: count
          in: query
          schema:
            type: integer
          required: true
          description: The number of passwords to generate
          example: 10
        - name: length
          in: query
          schema:
            type: integer
          required: true
          description: The length of the password to generate
          example: 12
        - name: complexity
          in: query
          schema:
            type: string
          required: true
          description: The complexity of the password
          example: strong
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  passwords:
                    - password: aOwqDh0ZK*P;!M|%oiFYJ!IK%TMXQO
                      length: 30
                      metadata:
                        type: random
                        complexity: strong
                      analysis: null
                    - password: Wo:)*V2nMakoVI78[fKu|QDI.E45p|
                      length: 30
                      metadata:
                        type: random
                        complexity: strong
                      analysis: null
                    - password: '%XqlsK2qN.9>*&jk6gYIG.[aE,hiRc'
                      length: 30
                      metadata:
                        type: random
                        complexity: strong
                      analysis: null
                    - password: WQNY0{R~(G99uc&i62Mve).n<|xt=F
                      length: 30
                      metadata:
                        type: random
                        complexity: strong
                      analysis: null
                    - password: 2$m-&z9!5$c3QlxQP{h#@0x~'M/h]T
                      length: 30
                      metadata:
                        type: random
                        complexity: strong
                      analysis: null
                    - password: y]e_H)/z2yzbr{4C&hHOb[Q:#/$Hml
                      length: 30
                      metadata:
                        type: random
                        complexity: strong
                      analysis: null
                    - password: +iZ,<<+_MR:jJ,JbXTN*3Z,xLo'=@E
                      length: 30
                      metadata:
                        type: random
                        complexity: strong
                      analysis: null
                    - password: x=e6H^U;ajD+)h5Z8$7Wy)^Ob8ERw'
                      length: 30
                      metadata:
                        type: random
                        complexity: strong
                      analysis: null
                    - password: +p!SGSnR*JNl}/[#oVQy~ZxtoZU}F+
                      length: 30
                      metadata:
                        type: random
                        complexity: strong
                      analysis: null
                    - password: '%h:23-bMb0;?QWL)chKm8{>%)mN:EO'
                      length: 30
                      metadata:
                        type: random
                        complexity: strong
                      analysis: null
                  count: 10
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
